#!/bin/false

import os
import os.path
import glob


Import('env')

dir_path = Dir('.').abspath

# Environment for base library
core_env = env.Clone();

core_env.sources = sorted(glob.glob(dir_path + "/*.cpp"));
core_env.headers = sorted(glob.glob(dir_path + "/*.h"));

env.sources += core_env.sources;
env.headers += core_env.headers;

## Shared lib
objects = []
core_env.add_source_files(objects, core_env.sources, shared=False);

core_env.bins = [];
# Cavity2D
core_env.program = core_env.Program('#bin/kel-gasp', [objects]);
core_env.bins += core_env.program;

# Set Alias
env.Alias('bins', [core_env.bins]);

env.targets += ['bins'];

# Install
env.Install('$prefix/bin', [core_env.bins]);
